import Vue from 'vue';
import { Button, Tabbar, TabbarItem, NavBar, Icon, Search, Image as VanImage, Popup, Swipe, SwipeItem, Lazyload, Grid, GridItem, Sticky, Divider, SubmitBar } from 'vant';
import 'vant/lib/index.css';
Vue.use(Button);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(NavBar);
Vue.use(Icon);
Vue.use(Search);
Vue.use(VanImage);
Vue.use(Popup);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Lazyload);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Sticky);
Vue.use(Divider);
Vue.use(SubmitBar);
