import Vue from 'vue';
import { Sku, GoodsAction, GoodsActionButton, GoodsActionIcon, List, PullRefresh, DropdownMenu, DropdownItem, Form, Field, Button, Tabbar, TabbarItem, NavBar, Icon, Search, Image as VanImage, Popup, Swipe, SwipeItem, Lazyload, Grid, GridItem, Sticky, Divider, SubmitBar } from 'vant';
import 'vant/lib/index.css';
Vue.use(Button);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(NavBar);
Vue.use(Icon);
Vue.use(Search);
Vue.use(VanImage);
Vue.use(Popup);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Lazyload);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Sticky);
Vue.use(Divider);
Vue.use(SubmitBar);
Vue.use(Form);
Vue.use(Field);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(PullRefresh);
Vue.use(List);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Sku);